### ISSUE TITLE
Ability to change the cluster icon

### ISSUE THREAD

**Issue by ppavlov** [Avalith/MarkerClusterGroup#3]
I believe that currently the cluster icons are managed by /js/lib/MarkerClusterGroup/MarkerClusterGroup.css which allows one to override the existing "icon", but probably far better solution will be to pass a structure that defines the different styling in a MarkerClusterer fashion. Some documentation around this will be greatly appreciated.

**Comment by karamfil** [comment]
Currently it works depending on how many digits there are in a cluster and styling in css is the fastest most performant solution.
